name: Build

on:
  workflow_call:
    inputs:
      versionPrefix:
        required: true
        type: string
      versionSuffix:
        required: true
        type: string

jobs:
  build-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - run: dotnet restore NuGetOnly.slnf

    - run: dotnet build NuGetOnly.slnf -c Release --no-restore -p:VersionPrefix=${{ inputs.versionPrefix }} -p:VersionSuffix=${{ inputs.versionSuffix }}

    - run: dotnet pack NuGetOnly.slnf -c Release --no-build -o ./nupkg -p:VersionPrefix=${{ inputs.versionPrefix }} -p:VersionSuffix=${{ inputs.versionSuffix }}

    - uses: actions/upload-artifact@v7
      with:
        name: nupkg
        path: nupkg/*.nupkg

  build-tool:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - run: dotnet restore ToolOnly.slnf

    - run: dotnet build ToolOnly.slnf -c Release --no-restore -p:VersionPrefix=${{ inputs.versionPrefix }} -p:VersionSuffix=${{ inputs.versionSuffix }}

    - run: dotnet pack ToolOnly.slnf -c Release -o ./tool -p:VersionPrefix=${{ inputs.versionPrefix }} -p:VersionSuffix=${{ inputs.versionSuffix }}

    - uses: actions/upload-artifact@v7
      with:
        name: tool
        path: tool/*.nupkg
