name: Build

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-nuget:
    runs-on: ubuntu-latest
    steps:
    - name: Restore versioned sources
      uses: actions/cache/restore@v4
      with:
        path: |
          !**/.git
          **/*
        key: cache-${{ github.sha }}
        enableCrossOsArchive: true
    - uses: actions/setup-dotnet@v4
    - run: dotnet restore NuGetOnly.slnf
    - run: dotnet build NuGetOnly.slnf -c Release --no-restore
    - run: dotnet pack NuGetOnly.slnf -c Release --no-build -o ./nupkg -p:Version=${{ inputs.tag }}
    - uses: actions/cache/save@v4
      with:
        path: nupkg
        key: cache-${{ github.sha }}
        enableCrossOsArchive: true

  build-tool:
    runs-on: ubuntu-latest
    steps:
    - name: Restore versioned sources
      uses: actions/cache/restore@v4
      with:
        path: |
          !**/.git
          **/*
        key: cache-${{ github.sha }}
        enableCrossOsArchive: true
    - uses: actions/setup-dotnet@v4
    - run: dotnet restore ToolOnly.slnf
    - run: dotnet build ToolOnly.slnf -c Release --no-restore
    - run: dotnet pack ToolOnly.slnf -c Release --no-build -o ./tool -p:Version=${{ inputs.tag }}
    - uses: actions/cache/save@v4
      with:
        path: tool
        key: cache-${{ github.sha }}
        enableCrossOsArchive: true
