name: Publish

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      nuget-api-key:
        required: true

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - uses: actions/download-artifact@v8
      with:
        name: nupkg
        path: nupkg

    - run: dotnet nuget push "nupkg/Creedengo.${{ inputs.tag }}.nupkg" -k "${{ secrets.nuget-api-key }}" -s https://api.nuget.org/v3/index.json

  publish-tool:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - uses: actions/download-artifact@v8
      with:
        name: tool
        path: tool

    - run: dotnet nuget push "tool/Creedengo.Tool.${{ inputs.tag }}.nupkg" -k "${{ secrets.nuget-api-key }}" -s https://api.nuget.org/v3/index.json
