name: Publish

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      nuget-api-key:
        required: true

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache/restore@v4
      with:
        path: nupkg
        key: cache-${{ github.sha }}
        enableCrossOsArchive: true

    - run: echo "PACKAGE=$(find . -name 'Creedengo.${{ inputs.tag }}.nupkg' | head -n 1)" >> $GITHUB_ENV
  
    - run: dotnet nuget push ${{ env.PACKAGE }} -k "${{ secrets.nuget-api-key }}" -s https://api.nuget.org/v3/index.json
  
  publish-tool:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache/restore@v4
      with:
        path: tool
        key: cache-${{ github.sha }}
        enableCrossOsArchive: true

    - run: echo "PACKAGE=$(find . -name 'Creedengo.Tool.${{ inputs.tag }}.nupkg' | head -n 1)" >> $GITHUB_ENV
  
    - run: dotnet nuget push ${{ env.PACKAGE }} -k "${{ secrets.nuget-api-key }}" -s https://api.nuget.org/v3/index.json
