name: Publish VSIX

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      vsmarketplace-api-key:
        required: true

jobs:
  publish-vsix:
    if: ${{ inputs.tag == inputs.version }}
    runs-on: windows-latest
    steps:
    - uses: actions/cache/restore@v4
      with:
        path: vsix
        key: cache-${{ github.sha }}
        enableCrossOsArchive: true
    - uses: cezarypiatek/VsixPublisherAction@1.1
      with:
        extension-file: vsix/EcoCode.vsix
        publish-manifest-file: vsix/publishManifest.json
        personal-access-code: ${{ secrets.vsmarketplace-api-key }}
