name: Build and Test
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
  
permissions:
  contents: read

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
    - run: dotnet restore NuGetOnly.slnf
    - run: dotnet build NuGetOnly.slnf -c Release --no-restore
    - run: dotnet pack NuGetOnly.slnf -c Release --no-build
    - run: dotnet test NuGetOnly.slnf -c Release --no-build --logger "trx;LogFileName=test_results.trx"
    - uses: actions/upload-artifact@v4
      if: always() # Ensure this step runs even if the test step fails
      with:
        name: Test Results
        path: '**/test_results.trx'

  build-vsix:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
    - run: dotnet restore VsixOnly.slnf
    - run: dotnet build VsixOnly.slnf -c Release --no-restore
