name: Build and Test
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
  
permissions:
  contents: read

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
    - run: dotnet restore TestsOnly.slnf
    - run: dotnet build TestsOnly.slnf -c Release --no-restore
    - run: dotnet test TestsOnly.slnf -c Release --no-build --logger "trx;LogFileName=test_results.trx" -p:CollectCoverage=true -p:Threshold=80 -p:CoverletOutputFormat='cobertura'
    - uses: danielpalme/ReportGenerator-GitHub-Action@5
      with:
        reports: '/home/runner/work/ecoCode-csharp/ecoCode-csharp/src/EcoCode.Tests/coverage.cobertura.xml'
        targetdir: 'CoverageReports'
        historydir: 'CoverageHistory'
        reporttypes: 'HtmlInline;Cobertura'  
    - uses: actions/upload-artifact@v4
      if: always() # Ensure this step runs even if the test step fails
      with:
        name: Test Results
        path: '**/test_results.trx'
    - uses: actions/upload-artifact@v4
      with:
        name: Coverage reports
        path: CoverageReports
