name: Create tag release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'

permissions:
  actions: write
  contents: write

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  versioning:
    uses: ./.github/workflows/01-versioning.yml

  build-nuget:
    needs: versioning
    uses: ./.github/workflows/02-build-nuget.yml
    with:
      tag: ${{ needs.versioning.outputs.tag }}

  build-vsix:
    needs: versioning
    uses: ./.github/workflows/03-build-vsix.yml
    with:
      tag: ${{ needs.versioning.outputs.tag }}

  publish-nuget:
    needs: [versioning, build-nuget, build-vsix]
    uses: ./.github/workflows/04-publish-nuget.yml
    with:
      tag: ${{ needs.versioning.outputs.tag }}
      version: ${{ needs.versioning.outputs.version }}

  publish-vsix:
    needs: [versioning, build-nuget, build-vsix]
    uses: ./.github/workflows/05-publish-vsix.yml
    with:
      tag: ${{ needs.versioning.outputs.tag }}
      version: ${{ needs.versioning.outputs.version }}

  create-release:
    needs: [publish-nuget, publish-vsix]
    uses: ./.github/workflows/06-create-release.yml
    with:
      tag: ${{ needs.versioning.outputs.tag }}
      version: ${{ needs.versioning.outputs.version }}
