name: Create manual VSIX release
on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build-vsix:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v4
    - uses: actions/checkout@v4
    - run: dotnet restore VsixOnly.slnf
    - uses: microsoft/setup-msbuild@v2
    - run: msbuild VsixOnly.slnf "-p:OutputPath=..\..\vsix;Configuration=Release"
    - uses: cezarypiatek/VsixPublisherAction@1.1
      with:
        extension-file: vsix\EcoCode.vsix
        publish-manifest-file: vsix\publishManifest.json
        personal-access-code: ${{ secrets.VSMARKETPLACE_API_KEY }}
