name: Create tag release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'

permissions:
  actions: write
  contents: write

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  versioning:
    uses: ./.github/workflows/01-versioning.yml

  build:
    needs: versioning
    uses: ./.github/workflows/02-build.yml
    with:
      tag: ${{ needs.versioning.outputs.tag }}

  publish:
    needs: [versioning, build]
    uses: ./.github/workflows/03-publish.yml
    with:
      tag: ${{ needs.versioning.outputs.tag }}
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}

  release:
    needs: publish
    uses: ./.github/workflows/04-release.yml
    with:
      tag: ${{ needs.versioning.outputs.tag }}
      version: ${{ needs.versioning.outputs.version }}
